name: "deploy"

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        uses: fjogeleit/http-request-action@v1.12.0
        with:
          url: ${{secrets.HOOKS_URL}}
          method: "POST"
